export interface PhoneCountry {
  iso: string
  name: string
  dial: string
  flag: string
  len: [number, number]
}

export const PHONE_COUNTRIES: PhoneCountry[] = [
  { iso: 'AF', name: 'Afghanistan',                      dial: '+93',    flag: '🇦🇫', len: [9,  9]  },
  { iso: 'AL', name: 'Albania',                          dial: '+355',   flag: '🇦🇱', len: [9,  9]  },
  { iso: 'DZ', name: 'Algeria',                          dial: '+213',   flag: '🇩🇿', len: [9,  9]  },
  { iso: 'AD', name: 'Andorra',                          dial: '+376',   flag: '🇦🇩', len: [6,  9]  },
  { iso: 'AO', name: 'Angola',                           dial: '+244',   flag: '🇦🇴', len: [9,  9]  },
  { iso: 'AG', name: 'Antigua and Barbuda',              dial: '+1268',  flag: '🇦🇬', len: [7,  7]  },
  { iso: 'AR', name: 'Argentina',                        dial: '+54',    flag: '🇦🇷', len: [10, 10] },
  { iso: 'AM', name: 'Armenia',                          dial: '+374',   flag: '🇦🇲', len: [8,  8]  },
  { iso: 'AU', name: 'Australia',                        dial: '+61',    flag: '🇦🇺', len: [9,  9]  },
  { iso: 'AT', name: 'Austria',                          dial: '+43',    flag: '🇦🇹', len: [10, 13] },
  { iso: 'AZ', name: 'Azerbaijan',                       dial: '+994',   flag: '🇦🇿', len: [9,  9]  },
  { iso: 'BS', name: 'Bahamas',                          dial: '+1242',  flag: '🇧🇸', len: [7,  7]  },
  { iso: 'BH', name: 'Bahrain',                          dial: '+973',   flag: '🇧🇭', len: [8,  8]  },
  { iso: 'BD', name: 'Bangladesh',                       dial: '+880',   flag: '🇧🇩', len: [10, 10] },
  { iso: 'BB', name: 'Barbados',                         dial: '+1246',  flag: '🇧🇧', len: [7,  7]  },
  { iso: 'BY', name: 'Belarus',                          dial: '+375',   flag: '🇧🇾', len: [9,  9]  },
  { iso: 'BE', name: 'Belgium',                          dial: '+32',    flag: '🇧🇪', len: [9,  9]  },
  { iso: 'BZ', name: 'Belize',                           dial: '+501',   flag: '🇧🇿', len: [7,  7]  },
  { iso: 'BJ', name: 'Benin',                            dial: '+229',   flag: '🇧🇯', len: [8,  8]  },
  { iso: 'BO', name: 'Bolivia',                          dial: '+591',   flag: '🇧🇴', len: [8,  8]  },
  { iso: 'BA', name: 'Bosnia and Herzegovina',           dial: '+387',   flag: '🇧🇦', len: [8,  8]  },
  { iso: 'BW', name: 'Botswana',                         dial: '+267',   flag: '🇧🇼', len: [8,  8]  },
  { iso: 'BR', name: 'Brazil',                           dial: '+55',    flag: '🇧🇷', len: [10, 11] },
  { iso: 'BN', name: 'Brunei',                           dial: '+673',   flag: '🇧🇳', len: [7,  7]  },
  { iso: 'BG', name: 'Bulgaria',                         dial: '+359',   flag: '🇧🇬', len: [9,  9]  },
  { iso: 'BF', name: 'Burkina Faso',                     dial: '+226',   flag: '🇧🇫', len: [8,  8]  },
  { iso: 'BI', name: 'Burundi',                          dial: '+257',   flag: '🇧🇮', len: [8,  8]  },
  { iso: 'KH', name: 'Cambodia',                         dial: '+855',   flag: '🇰🇭', len: [8,  9]  },
  { iso: 'CM', name: 'Cameroon',                         dial: '+237',   flag: '🇨🇲', len: [9,  9]  },
  { iso: 'CA', name: 'Canada',                           dial: '+1',     flag: '🇨🇦', len: [10, 10] },
  { iso: 'CV', name: 'Cape Verde',                       dial: '+238',   flag: '🇨🇻', len: [7,  7]  },
  { iso: 'CF', name: 'Central African Republic',         dial: '+236',   flag: '🇨🇫', len: [8,  8]  },
  { iso: 'TD', name: 'Chad',                             dial: '+235',   flag: '🇹🇩', len: [8,  8]  },
  { iso: 'CL', name: 'Chile',                            dial: '+56',    flag: '🇨🇱', len: [9,  9]  },
  { iso: 'CN', name: 'China',                            dial: '+86',    flag: '🇨🇳', len: [11, 11] },
  { iso: 'CO', name: 'Colombia',                         dial: '+57',    flag: '🇨🇴', len: [10, 10] },
  { iso: 'KM', name: 'Comoros',                          dial: '+269',   flag: '🇰🇲', len: [7,  7]  },
  { iso: 'CG', name: 'Congo',                            dial: '+242',   flag: '🇨🇬', len: [9,  9]  },
  { iso: 'CR', name: 'Costa Rica',                       dial: '+506',   flag: '🇨🇷', len: [8,  8]  },
  { iso: 'HR', name: 'Croatia',                          dial: '+385',   flag: '🇭🇷', len: [8,  9]  },
  { iso: 'CU', name: 'Cuba',                             dial: '+53',    flag: '🇨🇺', len: [8,  8]  },
  { iso: 'CY', name: 'Cyprus',                           dial: '+357',   flag: '🇨🇾', len: [8,  8]  },
  { iso: 'CZ', name: 'Czech Republic',                   dial: '+420',   flag: '🇨🇿', len: [9,  9]  },
  { iso: 'CD', name: 'DR Congo',                         dial: '+243',   flag: '🇨🇩', len: [9,  9]  },
  { iso: 'DK', name: 'Denmark',                          dial: '+45',    flag: '🇩🇰', len: [8,  8]  },
  { iso: 'DJ', name: 'Djibouti',                         dial: '+253',   flag: '🇩🇯', len: [8,  8]  },
  { iso: 'DM', name: 'Dominica',                         dial: '+1767',  flag: '🇩🇲', len: [7,  7]  },
  { iso: 'DO', name: 'Dominican Republic',               dial: '+1809',  flag: '🇩🇴', len: [7,  7]  },
  { iso: 'EC', name: 'Ecuador',                          dial: '+593',   flag: '🇪🇨', len: [9,  9]  },
  { iso: 'EG', name: 'Egypt',                            dial: '+20',    flag: '🇪🇬', len: [10, 10] },
  { iso: 'SV', name: 'El Salvador',                      dial: '+503',   flag: '🇸🇻', len: [8,  8]  },
  { iso: 'GQ', name: 'Equatorial Guinea',                dial: '+240',   flag: '🇬🇶', len: [9,  9]  },
  { iso: 'ER', name: 'Eritrea',                          dial: '+291',   flag: '🇪🇷', len: [7,  7]  },
  { iso: 'EE', name: 'Estonia',                          dial: '+372',   flag: '🇪🇪', len: [7,  8]  },
  { iso: 'SZ', name: 'Eswatini',                         dial: '+268',   flag: '🇸🇿', len: [8,  8]  },
  { iso: 'ET', name: 'Ethiopia',                         dial: '+251',   flag: '🇪🇹', len: [9,  9]  },
  { iso: 'FJ', name: 'Fiji',                             dial: '+679',   flag: '🇫🇯', len: [7,  7]  },
  { iso: 'FI', name: 'Finland',                          dial: '+358',   flag: '🇫🇮', len: [9,  10] },
  { iso: 'FR', name: 'France',                           dial: '+33',    flag: '🇫🇷', len: [9,  9]  },
  { iso: 'GA', name: 'Gabon',                            dial: '+241',   flag: '🇬🇦', len: [8,  8]  },
  { iso: 'GM', name: 'Gambia',                           dial: '+220',   flag: '🇬🇲', len: [7,  7]  },
  { iso: 'GE', name: 'Georgia',                          dial: '+995',   flag: '🇬🇪', len: [9,  9]  },
  { iso: 'DE', name: 'Germany',                          dial: '+49',    flag: '🇩🇪', len: [10, 12] },
  { iso: 'GH', name: 'Ghana',                            dial: '+233',   flag: '🇬🇭', len: [9,  9]  },
  { iso: 'GR', name: 'Greece',                           dial: '+30',    flag: '🇬🇷', len: [10, 10] },
  { iso: 'GD', name: 'Grenada',                          dial: '+1473',  flag: '🇬🇩', len: [7,  7]  },
  { iso: 'GT', name: 'Guatemala',                        dial: '+502',   flag: '🇬🇹', len: [8,  8]  },
  { iso: 'GN', name: 'Guinea',                           dial: '+224',   flag: '🇬🇳', len: [9,  9]  },
  { iso: 'GW', name: 'Guinea-Bissau',                    dial: '+245',   flag: '🇬🇼', len: [7,  7]  },
  { iso: 'GY', name: 'Guyana',                           dial: '+592',   flag: '🇬🇾', len: [7,  7]  },
  { iso: 'HT', name: 'Haiti',                            dial: '+509',   flag: '🇭🇹', len: [8,  8]  },
  { iso: 'HN', name: 'Honduras',                         dial: '+504',   flag: '🇭🇳', len: [8,  8]  },
  { iso: 'HK', name: 'Hong Kong',                        dial: '+852',   flag: '🇭🇰', len: [8,  8]  },
  { iso: 'HU', name: 'Hungary',                          dial: '+36',    flag: '🇭🇺', len: [9,  9]  },
  { iso: 'IS', name: 'Iceland',                          dial: '+354',   flag: '🇮🇸', len: [7,  7]  },
  { iso: 'IN', name: 'India',                            dial: '+91',    flag: '🇮🇳', len: [10, 10] },
  { iso: 'ID', name: 'Indonesia',                        dial: '+62',    flag: '🇮🇩', len: [9,  12] },
  { iso: 'IR', name: 'Iran',                             dial: '+98',    flag: '🇮🇷', len: [10, 10] },
  { iso: 'IQ', name: 'Iraq',                             dial: '+964',   flag: '🇮🇶', len: [10, 10] },
  { iso: 'IE', name: 'Ireland',                          dial: '+353',   flag: '🇮🇪', len: [9,  9]  },
  { iso: 'IL', name: 'Israel',                           dial: '+972',   flag: '🇮🇱', len: [9,  9]  },
  { iso: 'IT', name: 'Italy',                            dial: '+39',    flag: '🇮🇹', len: [9,  10] },
  { iso: 'CI', name: 'Ivory Coast',                      dial: '+225',   flag: '🇨🇮', len: [10, 10] },
  { iso: 'JM', name: 'Jamaica',                          dial: '+1876',  flag: '🇯🇲', len: [7,  7]  },
  { iso: 'JP', name: 'Japan',                            dial: '+81',    flag: '🇯🇵', len: [10, 10] },
  { iso: 'JO', name: 'Jordan',                           dial: '+962',   flag: '🇯🇴', len: [9,  9]  },
  { iso: 'KZ', name: 'Kazakhstan',                       dial: '+7',     flag: '🇰🇿', len: [10, 10] },
  { iso: 'KE', name: 'Kenya',                            dial: '+254',   flag: '🇰🇪', len: [9,  9]  },
  { iso: 'KI', name: 'Kiribati',                         dial: '+686',   flag: '🇰🇮', len: [5,  8]  },
  { iso: 'KW', name: 'Kuwait',                           dial: '+965',   flag: '🇰🇼', len: [8,  8]  },
  { iso: 'KG', name: 'Kyrgyzstan',                       dial: '+996',   flag: '🇰🇬', len: [9,  9]  },
  { iso: 'LA', name: 'Laos',                             dial: '+856',   flag: '🇱🇦', len: [8,  9]  },
  { iso: 'LV', name: 'Latvia',                           dial: '+371',   flag: '🇱🇻', len: [8,  8]  },
  { iso: 'LB', name: 'Lebanon',                          dial: '+961',   flag: '🇱🇧', len: [7,  8]  },
  { iso: 'LS', name: 'Lesotho',                          dial: '+266',   flag: '🇱🇸', len: [8,  8]  },
  { iso: 'LR', name: 'Liberia',                          dial: '+231',   flag: '🇱🇷', len: [8,  8]  },
  { iso: 'LY', name: 'Libya',                            dial: '+218',   flag: '🇱🇾', len: [9,  10] },
  { iso: 'LI', name: 'Liechtenstein',                    dial: '+423',   flag: '🇱🇮', len: [7,  9]  },
  { iso: 'LT', name: 'Lithuania',                        dial: '+370',   flag: '🇱🇹', len: [8,  8]  },
  { iso: 'LU', name: 'Luxembourg',                       dial: '+352',   flag: '🇱🇺', len: [9,  9]  },
  { iso: 'MO', name: 'Macao',                            dial: '+853',   flag: '🇲🇴', len: [8,  8]  },
  { iso: 'MG', name: 'Madagascar',                       dial: '+261',   flag: '🇲🇬', len: [9,  9]  },
  { iso: 'MW', name: 'Malawi',                           dial: '+265',   flag: '🇲🇼', len: [9,  9]  },
  { iso: 'MY', name: 'Malaysia',                         dial: '+60',    flag: '🇲🇾', len: [9,  10] },
  { iso: 'MV', name: 'Maldives',                         dial: '+960',   flag: '🇲🇻', len: [7,  7]  },
  { iso: 'ML', name: 'Mali',                             dial: '+223',   flag: '🇲🇱', len: [8,  8]  },
  { iso: 'MT', name: 'Malta',                            dial: '+356',   flag: '🇲🇹', len: [8,  8]  },
  { iso: 'MH', name: 'Marshall Islands',                 dial: '+692',   flag: '🇲🇭', len: [7,  7]  },
  { iso: 'MR', name: 'Mauritania',                       dial: '+222',   flag: '🇲🇷', len: [8,  8]  },
  { iso: 'MU', name: 'Mauritius',                        dial: '+230',   flag: '🇲🇺', len: [8,  8]  },
  { iso: 'MX', name: 'Mexico',                           dial: '+52',    flag: '🇲🇽', len: [10, 10] },
  { iso: 'FM', name: 'Micronesia',                       dial: '+691',   flag: '🇫🇲', len: [7,  7]  },
  { iso: 'MD', name: 'Moldova',                          dial: '+373',   flag: '🇲🇩', len: [8,  8]  },
  { iso: 'MC', name: 'Monaco',                           dial: '+377',   flag: '🇲🇨', len: [8,  9]  },
  { iso: 'MN', name: 'Mongolia',                         dial: '+976',   flag: '🇲🇳', len: [8,  8]  },
  { iso: 'ME', name: 'Montenegro',                       dial: '+382',   flag: '🇲🇪', len: [8,  8]  },
  { iso: 'MA', name: 'Morocco',                          dial: '+212',   flag: '🇲🇦', len: [9,  9]  },
  { iso: 'MZ', name: 'Mozambique',                       dial: '+258',   flag: '🇲🇿', len: [9,  9]  },
  { iso: 'MM', name: 'Myanmar',                          dial: '+95',    flag: '🇲🇲', len: [9,  10] },
  { iso: 'NA', name: 'Namibia',                          dial: '+264',   flag: '🇳🇦', len: [9,  9]  },
  { iso: 'NR', name: 'Nauru',                            dial: '+674',   flag: '🇳🇷', len: [7,  7]  },
  { iso: 'NP', name: 'Nepal',                            dial: '+977',   flag: '🇳🇵', len: [10, 10] },
  { iso: 'NL', name: 'Netherlands',                      dial: '+31',    flag: '🇳🇱', len: [9,  9]  },
  { iso: 'NZ', name: 'New Zealand',                      dial: '+64',    flag: '🇳🇿', len: [8,  9]  },
  { iso: 'NI', name: 'Nicaragua',                        dial: '+505',   flag: '🇳🇮', len: [8,  8]  },
  { iso: 'NE', name: 'Niger',                            dial: '+227',   flag: '🇳🇪', len: [8,  8]  },
  { iso: 'NG', name: 'Nigeria',                          dial: '+234',   flag: '🇳🇬', len: [10, 10] },
  { iso: 'KP', name: 'North Korea',                      dial: '+850',   flag: '🇰🇵', len: [8,  8]  },
  { iso: 'MK', name: 'North Macedonia',                  dial: '+389',   flag: '🇲🇰', len: [8,  8]  },
  { iso: 'NO', name: 'Norway',                           dial: '+47',    flag: '🇳🇴', len: [8,  8]  },
  { iso: 'OM', name: 'Oman',                             dial: '+968',   flag: '🇴🇲', len: [8,  8]  },
  { iso: 'PK', name: 'Pakistan',                         dial: '+92',    flag: '🇵🇰', len: [10, 10] },
  { iso: 'PW', name: 'Palau',                            dial: '+680',   flag: '🇵🇼', len: [7,  7]  },
  { iso: 'PS', name: 'Palestine',                        dial: '+970',   flag: '🇵🇸', len: [9,  9]  },
  { iso: 'PA', name: 'Panama',                           dial: '+507',   flag: '🇵🇦', len: [8,  8]  },
  { iso: 'PG', name: 'Papua New Guinea',                 dial: '+675',   flag: '🇵🇬', len: [8,  8]  },
  { iso: 'PY', name: 'Paraguay',                         dial: '+595',   flag: '🇵🇾', len: [9,  9]  },
  { iso: 'PE', name: 'Peru',                             dial: '+51',    flag: '🇵🇪', len: [9,  9]  },
  { iso: 'PH', name: 'Philippines',                      dial: '+63',    flag: '🇵🇭', len: [10, 10] },
  { iso: 'PL', name: 'Poland',                           dial: '+48',    flag: '🇵🇱', len: [9,  9]  },
  { iso: 'PT', name: 'Portugal',                         dial: '+351',   flag: '🇵🇹', len: [9,  9]  },
  { iso: 'QA', name: 'Qatar',                            dial: '+974',   flag: '🇶🇦', len: [8,  8]  },
  { iso: 'RO', name: 'Romania',                          dial: '+40',    flag: '🇷🇴', len: [9,  9]  },
  { iso: 'RU', name: 'Russia',                           dial: '+7',     flag: '🇷🇺', len: [10, 10] },
  { iso: 'RW', name: 'Rwanda',                           dial: '+250',   flag: '🇷🇼', len: [9,  9]  },
  { iso: 'KN', name: 'Saint Kitts and Nevis',            dial: '+1869',  flag: '🇰🇳', len: [7,  7]  },
  { iso: 'LC', name: 'Saint Lucia',                      dial: '+1758',  flag: '🇱🇨', len: [7,  7]  },
  { iso: 'VC', name: 'Saint Vincent and the Grenadines', dial: '+1784',  flag: '🇻🇨', len: [7,  7]  },
  { iso: 'WS', name: 'Samoa',                            dial: '+685',   flag: '🇼🇸', len: [5,  7]  },
  { iso: 'ST', name: 'Sao Tome and Principe',            dial: '+239',   flag: '🇸🇹', len: [7,  7]  },
  { iso: 'SA', name: 'Saudi Arabia',                     dial: '+966',   flag: '🇸🇦', len: [9,  9]  },
  { iso: 'SN', name: 'Senegal',                          dial: '+221',   flag: '🇸🇳', len: [9,  9]  },
  { iso: 'RS', name: 'Serbia',                           dial: '+381',   flag: '🇷🇸', len: [9,  9]  },
  { iso: 'SC', name: 'Seychelles',                       dial: '+248',   flag: '🇸🇨', len: [7,  7]  },
  { iso: 'SL', name: 'Sierra Leone',                     dial: '+232',   flag: '🇸🇱', len: [8,  8]  },
  { iso: 'SG', name: 'Singapore',                        dial: '+65',    flag: '🇸🇬', len: [8,  8]  },
  { iso: 'SK', name: 'Slovakia',                         dial: '+421',   flag: '🇸🇰', len: [9,  9]  },
  { iso: 'SI', name: 'Slovenia',                         dial: '+386',   flag: '🇸🇮', len: [8,  8]  },
  { iso: 'SB', name: 'Solomon Islands',                  dial: '+677',   flag: '🇸🇧', len: [7,  7]  },
  { iso: 'SO', name: 'Somalia',                          dial: '+252',   flag: '🇸🇴', len: [7,  8]  },
  { iso: 'ZA', name: 'South Africa',                     dial: '+27',    flag: '🇿🇦', len: [9,  9]  },
  { iso: 'KR', name: 'South Korea',                      dial: '+82',    flag: '🇰🇷', len: [9,  10] },
  { iso: 'SS', name: 'South Sudan',                      dial: '+211',   flag: '🇸🇸', len: [9,  9]  },
  { iso: 'ES', name: 'Spain',                            dial: '+34',    flag: '🇪🇸', len: [9,  9]  },
  { iso: 'LK', name: 'Sri Lanka',                        dial: '+94',    flag: '🇱🇰', len: [9,  9]  },
  { iso: 'SD', name: 'Sudan',                            dial: '+249',   flag: '🇸🇩', len: [9,  9]  },
  { iso: 'SR', name: 'Suriname',                         dial: '+597',   flag: '🇸🇷', len: [7,  7]  },
  { iso: 'SE', name: 'Sweden',                           dial: '+46',    flag: '🇸🇪', len: [9,  9]  },
  { iso: 'CH', name: 'Switzerland',                      dial: '+41',    flag: '🇨🇭', len: [9,  9]  },
  { iso: 'SY', name: 'Syria',                            dial: '+963',   flag: '🇸🇾', len: [9,  9]  },
  { iso: 'TW', name: 'Taiwan',                           dial: '+886',   flag: '🇹🇼', len: [9,  9]  },
  { iso: 'TJ', name: 'Tajikistan',                       dial: '+992',   flag: '🇹🇯', len: [9,  9]  },
  { iso: 'TZ', name: 'Tanzania',                         dial: '+255',   flag: '🇹🇿', len: [9,  9]  },
  { iso: 'TH', name: 'Thailand',                         dial: '+66',    flag: '🇹🇭', len: [9,  9]  },
  { iso: 'TL', name: 'Timor-Leste',                      dial: '+670',   flag: '🇹🇱', len: [8,  8]  },
  { iso: 'TG', name: 'Togo',                             dial: '+228',   flag: '🇹🇬', len: [8,  8]  },
  { iso: 'TO', name: 'Tonga',                            dial: '+676',   flag: '🇹🇴', len: [7,  7]  },
  { iso: 'TT', name: 'Trinidad and Tobago',              dial: '+1868',  flag: '🇹🇹', len: [7,  7]  },
  { iso: 'TN', name: 'Tunisia',                          dial: '+216',   flag: '🇹🇳', len: [8,  8]  },
  { iso: 'TR', name: 'Turkey',                           dial: '+90',    flag: '🇹🇷', len: [10, 10] },
  { iso: 'TM', name: 'Turkmenistan',                     dial: '+993',   flag: '🇹🇲', len: [8,  8]  },
  { iso: 'TV', name: 'Tuvalu',                           dial: '+688',   flag: '🇹🇻', len: [5,  6]  },
  { iso: 'AE', name: 'UAE',                              dial: '+971',   flag: '🇦🇪', len: [9,  9]  },
  { iso: 'UG', name: 'Uganda',                           dial: '+256',   flag: '🇺🇬', len: [9,  9]  },
  { iso: 'UA', name: 'Ukraine',                          dial: '+380',   flag: '🇺🇦', len: [9,  9]  },
  { iso: 'GB', name: 'United Kingdom',                   dial: '+44',    flag: '🇬🇧', len: [10, 10] },
  { iso: 'UY', name: 'Uruguay',                          dial: '+598',   flag: '🇺🇾', len: [9,  9]  },
  { iso: 'UZ', name: 'Uzbekistan',                       dial: '+998',   flag: '🇺🇿', len: [9,  9]  },
  { iso: 'VU', name: 'Vanuatu',                          dial: '+678',   flag: '🇻🇺', len: [7,  7]  },
  { iso: 'VE', name: 'Venezuela',                        dial: '+58',    flag: '🇻🇪', len: [10, 10] },
  { iso: 'VN', name: 'Vietnam',                          dial: '+84',    flag: '🇻🇳', len: [9,  10] },
  { iso: 'YE', name: 'Yemen',                            dial: '+967',   flag: '🇾🇪', len: [9,  9]  },
  { iso: 'ZM', name: 'Zambia',                           dial: '+260',   flag: '🇿🇲', len: [9,  9]  },
  { iso: 'ZW', name: 'Zimbabwe',                         dial: '+263',   flag: '🇿🇼', len: [9,  9]  },
]

export const SORTED_BY_DIAL = [...PHONE_COUNTRIES].sort((a, b) => b.dial.length - a.dial.length)

export function parseMobile(value: string): { country: PhoneCountry | null; number: string } {
  for (const c of SORTED_BY_DIAL) {
    if (value.startsWith(c.dial)) {
      return { country: c, number: value.slice(c.dial.length) }
    }
  }
  return { country: null, number: value }
}
